# Generated by Django 5.1.4 on 2025-12-26 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('rue', models.CharField(max_length=200)),
                ('code_postal', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=150)),
                ('numero', models.CharField(default='TEMP', max_length=50)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='rh.employeur')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_employe', models.CharField(max_length=100)),
                ('prenom_employe', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=150)),
                ('numero_employe', models.CharField(max_length=50)),
                ('date_reference', models.DateField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('supprime_pour_employeur', models.BooleanField(default=False)),
                ('reponse_employeur', models.TextField(blank=True, null=True)),
                ('ancienne_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_donnees', to='rh.employeur')),
                ('nouvelle_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_recues', to='rh.employeur')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_employe', models.CharField(max_length=100)),
                ('prenom_employe', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=150)),
                ('numero_employe', models.CharField(max_length=50)),
                ('date_transfert', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('supprime_pour_employeur', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('ancienne_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_envoyes', to='rh.employeur')),
                ('nouvelle_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_recus', to='rh.employeur')),
            ],
        ),
    ]
