# Generated by Django 5.1.4 on 2025-12-26 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='employeur',
            name='code_postal',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Code postal canadien invalide (ex: H1A 2B3)', regex='^[A-Za-z]\\d[A-Za-z][ -]?\\d[A-Za-z]\\d$')]),
        ),
        migrations.AlterField(
            model_name='employeur',
            name='province',
            field=models.CharField(choices=[('QC', 'Québec'), ('ON', 'Ontario'), ('BC', 'Colombie-Britannique'), ('AB', 'Alberta'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('NS', 'Nouvelle-Écosse'), ('NB', 'Nouveau-Brunswick'), ('PE', 'Île-du-Prince-Édouard'), ('NL', 'Terre-Neuve-et-Labrador'), ('NT', 'Territoires du Nord-Ouest'), ('NU', 'Nunavut'), ('YT', 'Yukon')], max_length=2),
        ),
        migrations.AlterField(
            model_name='employeur',
            name='rue',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Adresse invalide', regex="^[0-9A-Za-zÀ-ÿ\\s,'\\-]+$")]),
        ),
        migrations.AlterField(
            model_name='employeur',
            name='telephone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone canadien invalide', regex='^\\+?1?\\s?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')]),
        ),
    ]
