# Generated by Django 5.1.4 on 2026-01-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_employeur_logo_alter_employeur_code_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='signature_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfert',
            name='signature_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
