# Generated by Django 5.1.4 on 2026-01-05 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_transfert_signature_image_transfert_signature_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('transfert', 'Transfert'), ('reference', 'Référence')], max_length=20)),
                ('action', models.CharField(choices=[('envoye', 'Envoyé'), ('recu', 'Reçu'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('supprime', 'Supprimé')], max_length=20)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='rh.employeur')),
            ],
        ),
    ]
