# Generated by Django 5.1.4 on 2026-01-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_historiqueaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueaction',
            name='action',
            field=models.CharField(choices=[('envoye', 'Envoyé'), ('recu', 'Reçu'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('supprime', 'Supprimé'), ('modifie', 'Modifié')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='type_action',
            field=models.CharField(choices=[('transfert', 'Transfert'), ('reference', 'Référence'), ('profil', 'Profil')], max_length=20),
        ),
    ]
