# Generated by Django 5.1.4 on 2026-01-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_alter_historiqueaction_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiqueaction',
            options={'verbose_name': 'Historique', 'verbose_name_plural': 'Historiques'},
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='action',
            field=models.CharField(choices=[('cree', 'Créé'), ('modifie', 'Modifié'), ('supprime', 'Supprimé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='date_action',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
