# Generated by Django 5.1.4 on 2026-01-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_alter_employeur_latitude_alter_employeur_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfert',
            name='signature_image',
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='signature_nom',
        ),
        migrations.AddField(
            model_name='transfert',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfert',
            name='nas',
            field=models.CharField(blank=True, help_text='NAS requis uniquement si autre nationalité', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='transfert',
            name='statut_canadien',
            field=models.CharField(choices=[('canadien', 'Canadien / Résident permanent'), ('etranger', 'Autre nationalité')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
