# Generated by Django 5.1.4 on 2026-01-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_remove_transfert_signature_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='type_operation',
            field=models.CharField(choices=[('transfert', 'Transfert'), ('embauche', 'Embauche')], default='transfert', max_length=10),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='numero_employe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
